package com.vito.base.ui.fragments;

import android.support.v4.app.Fragment;
import android.text.TextUtils;
import android.util.Log;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SwCity
//  @ File Name : FragmentFactory.java
//  @ Date : 2015/7/29
//  @ Author : lennon
//
//


/** */
public class FragmentFactory {
    /** */
    private static FragmentFactory mInstance = null;

    /** */
    public static FragmentFactory getInstance() {
        if (mInstance == null) {
            mInstance = new FragmentFactory();
        }
        return mInstance;
    }

    /** */
    public BaseFragment createFragment(String packageName, String name) {
        try {
            String fragmentClassName = "";
            if (!TextUtils.isEmpty(packageName)) {
                fragmentClassName = packageName + '.' + name;
            } else {
                fragmentClassName = name;
            }
            Log.d("lennon", "fragmentClassName = " + fragmentClassName);
            BaseFragment obj = (BaseFragment) Class.forName(fragmentClassName).newInstance();
            return obj;
        } catch (Exception e) {
            Log.d("lennon", "createFragment error");
            e.printStackTrace();
        }
        return null;
    }

    /** */
    public Fragment createFragment(String name) {
        return createFragment(this.getClass().getPackage().getName(), name);
    }

    public Fragment createFragment(Class T) {
        return createFragment("", T.getName());
    }
}
